export enum LookupEnum {
    Country = 'Country',
    Company = 'Company',
    Plan = 'Plan',
    Currency = 'Currency',
    Industry = 'Industry',
    MobileCode = 'MobileCode',
    BusinessRole = 'BusinessRole',
    Subscription = 'Subscription',
    CompanyType = 'CompanyType',
    CompanyHolding = 'CompanyHolding',
    CompanySubsidiary = 'CompanySubsidiary',
    Gender = 'Gender',
    MaritalStatus = 'MaritalStatus',
    Religion = 'Religion',
    MilitaryStatus = 'MilitaryStatus',
    BloodType = 'BloodType',
    AccountNature = 'AccountNature',
    JournalTemplateType = 'JournalTemplateType',
  }
  