name: 'Common Setup'
description: 'Reusable setup for Node.js and dependencies.'
inputs:
  node-version:
    description: 'Node.js version to use'
    required: true
    default: '18'

runs:
  using: 'composite'  # Use 'composite' for a reusable composite action
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

    - name: Clean npm cache
      shell: pwsh  # Specify PowerShell shell
      run: npm cache clean --force

    - name: Install dependencies
      shell: pwsh  # Specify PowerShell shell
      run: |
        npm config set legacy-peer-deps true
        npm install --force --verbose
        npm install @zxing/browser@latest @zxing/ngx-scanner@latest
