image: node:18.13.0

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies
          script:
            - npm install
            - npm install -g @angular/cli
            - cd projects/bussiness-owners
            - ng build --project bussiness-owners