image: node:17

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies
          caches:
            - node
          script:
            - npm install

      - step:
          name: Build Business Owners Project
          script:
            - ng build --project bussiness-owners

      - step:
          name: Build Admin Portal Project
          script:
            - ng build --project adminportal
