image: atlassian/default-image:3

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies
          script:
            - npm install
            - npm install -g @angular/cli
            - ng build --project bussiness-owners
