# bitbucket-pipelines.yml

image: node:17

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies
          caches:
            - node
          script:
            - npm install
            - npm install -g @angular/cli
            - export PATH=$(npm bin -g):$PATH
            - echo $PATH # Debug: Print the PATH to verify
            - ls -l $(npm bin -g) # List the contents of the global bin directory for verification

      - step:
          name: Build Business Owners Project
          caches:
            - node
          script:
            - export PATH=$(npm bin -g):$PATH
            - $(npm bin -g)/ng build --project bussiness-owners

      - step:
          name: Build Admin Portal Project
          caches:
            - node
          script:
            - export PATH=$(npm bin -g):$PATH
            - $(npm bin -g)/ng build --project adminportal
