# bitbucket-pipelines.yml

image: node:17

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies
          script:
            - npm install
            - npm install -g @angular/cli
            - export PATH="$PATH:$(npm bin)"
            # The above line ensures that the ng command is available

      - step:
          name: Build Business Owners Project
          script:
            - ng build --project bussiness-owners

      - step:
          name: Build Admin Portal Project
          script:
            - ng build --project adminportal
