---
image: node:17
pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies and Set Path
          script:
            - npm install
            - set PATH=%PATH%;C:\Users\Microtec-D8\AppData\Roaming\npm
      - step:
          name: Build Business Owners Project
          script:
            - ng.cmd build --project bussiness-owners
      - step:
          name: Build Admin Portal Project
          script:
            - ng.cmd build --project adminportal
