image: node:18.13.0

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies
          script:
            - npm install
            - npm install -g @angular/cli

      - step:
          name: Build Business Owners Project
          script:
            - npm run build --project bussiness-owners