image: node:18.13.0

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Installation
          caches:
            - node
          script:
            - npm install
          artifacts:
            - node_modules/** 
      - step:
          name: Build
          script:
            - npm run build:bussiness-owners
          artifacts:
            - dist/** 