# bitbucket-pipelines.yml

image: node:17.1.0

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies
          caches:
            - node
          script:
            - npm install
            - npm install -g @angular/cli

      - step:
          name: Build Business Owners Project
          caches:
            - node
          script:
            - npm install -g @angular/cli # Ensure Angular CLI is available
            - ng build --project bussiness-owners

      - step:
          name: Build Admin Portal Project
          caches:
            - node
          script:
            - npm install -g @angular/cli # Ensure Angular CLI is available
            - ng build --project adminportal