image: atlassian/default-image:3

pipelines:
  branches:
    moataz-ci/cd:
      - step:
          name: Install Dependencies
          script:
            - npm install
            - npm install -g @angular/cli

      - step:
          name: Build Business Owners Project
          script:
            - ng build --project bussiness-owners

      - step:
          name: Build Admin Portal Project
          script:
            - ng build --project adminportal
