image: node:18 

pipelines:
  default:
    - step:
        name: Build Frontend Projects
        caches:
          - node
        script:
          - echo "Installing dependencies..."
          - npm install 
          - echo "Building all projects..."
          - npm run build:bussiness-owners
          - npm run build:adminportal
          - npm run build:inventory
          - npm run build:hr
          - npm run build:erp
          - npm run build:sales
          - npm run build:finance
          - npm run build:purchase
          - npm run build:accounting
        artifacts:
          - frontadmin/**   
          - frontapps/**    