export class BreadcrumbLabel {

  static readonly ChartOfAccount = 'BreadCrumb.ChartOfAccount';
  static readonly TaxGroup = 'BreadCrumb.TaxGroup';
  static readonly TaxDefinition = 'BreadCrumb.TaxDefinition';
  static readonly CostCenter = 'BreadCrumb.CostCenter';
  static readonly JournalEntryList = 'BreadCrumb.JournalEntryList';
  static readonly JournalEntryAdd = 'BreadCrumb.JournalEntryAdd';
  static readonly JournalEntryView = 'BreadCrumb.JournalEntryView';
  static readonly JournalEntryEdit = 'BreadCrumb.JournalEntryEdit';
  static readonly TrialBalance = 'BreadCrumb.TrialBalance';
  static readonly AccountStatement = 'BreadCrumb.AccountStatement';
  static readonly JournalEntryOpeningBalance = 'BreadCrumb.JournalEntryOpeningBalance';
  static readonly AddJournalEntryOpeningBalance = 'BreadCrumb.AddJournalEntryOpeningBalance';
  static readonly EditJournalEntryOpeningBalance = 'BreadCrumb.EditJournalEntryOpeningBalance';
  static readonly ViewJournalEntryOpeningBalance = 'BreadCrumb.ViewJournalEntryOpeningBalance';
  static readonly CUSTOMER_DEFINITIONS ='BreadCrumb.CustomerDefinition';
  static readonly ADD_CUSTOMER_DEFINITIONS ='BreadCrumb.AddCustomerDefinition';
  static readonly EDIT_CUSTOMER_DEFINITIONS ='BreadCrumb.EditCustomerDefinition';
  static readonly customer_list ='BreadCrumb.CustomerCategory';
  static readonly customer_add ='BreadCrumb.AddCustomerCategory';
  static readonly customer_edit ='BreadCrumb.EditCustomerCategory';
  static readonly BANK_LIST ='BreadCrumb.BankDefinition';
  static readonly BANK_LIST_ADD ='BreadCrumb.AddBankDefinition';
  static readonly BANK_LIST_EDIT ='BreadCrumb.EditBankDefinition';
  static readonly PAYMENT_TERM_LIST ='BreadCrumb.PaymentTermList';
  static readonly TREASURY_LIST ='BreadCrumb.Treasury';
  static readonly vendor_list ='BreadCrumb.VendorCategory';
  static readonly vendor_Add ='BreadCrumb.AddVendorCategory';
  static readonly vendor_Edit ='BreadCrumb.EditVendorCategory';
  static readonly VENDOR_DEFINITIONS ='BreadCrumb.VendorDefinitions';
  static readonly ADD_VENDOR_DEFINITIONS ='BreadCrumb.AddVendorDefinition';
  static readonly EDIT_VENDOR_DEFINITIONS ='BreadCrumb.EditVendorDefinition';

    static SUBSCRIPTION ='Subscription'
    static USERS = 'Users';
    static ADD_COMPANY = 'Add company';
    static COMPANY_LIST = 'Company list';
    static COMPANY_EDIT = 'Company Edit';
    static my_subscription = 'My Subscription';
    static ERP_USERS = 'ERP Users';
    static APP_STORE = 'App Store';
    static APP_STORE_Details = ' Details';
    static CART = 'Cart List';
    static DOMAIN = 'Domain Details';
    static Manage_Apps='Manage Apps';
    static BUSSINESS_OWNER ='Bussiness Owners';
    static MANAGE_BUSSINESS_OWNER ='Manage Bussiness Owners';
    static SUBDOMAIN_INFO ='Subdomain Info';
    static COMPANIES_INFO ='Company Info';
    static LICENCE_INFO ='licence Info';
    static USER_INFO ='USER Info';
    static APP_INFO ='APP Info';
    static tag_list ='Tag List';
    static calendar_list ='Financial Calender';

    static EMPLOYEE='Employees';
    static EMPLOYEE_ADD='Add Employee';
    static EMPLOYEE_VIEW='View Employee';
    static EMPLOYEE_EDIT='Edit Employee';
    static Add_Tag ='Add Tag';
    static EDIT_ADDRESS ='Edit Address';
    static EDIT_BRANCHES ='Edit Branches';
    static EDIT_HIERARCHY ='Edit Hierarchy';
    static EDIT_LEGAL ='Edit Legal';
    static EDIT_CONTACT ='Edit Contact';
    static ADD_CUSTOMER_OPENEING_BALANCE ='Add Customer Opening Balance';
    static CURRENCY_DEFINITION ='Currency Definition';
    static ADD_CURRENCY_DEFINITION ='Add Currency Definition';
    static CURRENCY_DEFINITION_LIST ='Currency Definition List';
    static CURRENCY_CONVERSION ='Currency Conversion';

    static COST_CENTER ='Cost Center';
  }