name: Setup Common

inputs:
  branch-name:
    required: false
    type: string
    default: "DevOps"

  environment-name:
    description: Environment name
    required: true
    type: string
    default: development    

  iis-app-name:
    required: true
    type: string

  iis-app-root-folder:
    required: true
    type: string

runs:
  using: 'composite'

  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ inputs.branch-name }}
        fetch-depth: 0

    - name: Set IIS Folder Variable
      shell: pwsh
      id: set_iis_folder
      run: |
          $currentDate = (Get-Date).ToString('yyyy-MM-dd_HH-mm')
          echo "IIS_FOLDER=${{ inputs.iis-app-root-folder }}\\${{ inputs.iis-app-name }}_$currentDate" >> $env:GITHUB_ENV

    - name: Create IIS Folder
      shell: pwsh
      run: |
        $folderPath = "$env:IIS_FOLDER"
        New-Item -Path $folderPath -ItemType Directory
        Write-Host "Created folder: $folderPath"

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Clean npm cache
      shell: pwsh  
      run: npm cache clean --force

    - name: Install dependencies
      shell: pwsh  
      run: |
        npm config set legacy-peer-deps true
        npm install --force --verbose
        npm install @zxing/browser@latest @zxing/ngx-scanner@latest

    - name: Build App
      shell: pwsh
      run: |
        $appName = '${{ inputs.iis-app-name }}'
        Write-Host "Building app: $appName"
        # Simulate build process
        # Replace the below command with actual build steps if needed
        # Example: `ng build $appName`
        Write-Host "App $appName built successfully."
