name: 'IIS Deployment'
description: 'Reusable action for IIS website deployment.'

inputs:
  app-name:
    description: 'Name of the app to deploy.'
    required: true
  source-path:
    description: 'Source directory for deployment files.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Stop Website in IIS
      shell: pwsh
      run: |
        Import-Module WebAdministration
        $appName = '${{ inputs.app-name }}'
        $website = Get-Website | Where-Object {$_.Name -eq $appName}
        if ($website) {
          Stop-Website -Name $appName
          Write-Host "Website '$appName' stopped."
        } else {
          Write-Host "Website '$appName' not found."
        }

    - name: Backup Website
      shell: pwsh
      run: |
        $appName = '${{ inputs.app-name }}'
        $sourcePath = "C:\inetpub\wwwroot\$appName"
        $destinationPath = "D:\Backup\$appName-$(Get-Date -Format yyyy-MM-dd)"
        if (Test-Path $sourcePath) {
          Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force
          Write-Host "Website '$appName' backed up to $destinationPath."
        } else {
          Write-Host "Website '$appName' not found in C:\inetpub\wwwroot."
        }

    - name: Remove Files from Website Directory
      shell: pwsh
      run: |
        $appName = '${{ inputs.app-name }}'
        $path = "C:\inetpub\wwwroot\$appName"
        if (Test-Path $path) {
          Remove-Item -Path $path\* -Recurse -Force
          Write-Host "Files removed from $path."
        } else {
          Write-Host "Website '$appName' directory not found."
        }

    - name: Copy Files to Website Directory
      shell: pwsh
      run: |
        $appName = '${{ inputs.app-name }}'
        $sourcePath = '${{ inputs.source-path }}'
        $destinationPath = "C:\inetpub\wwwroot\$appName"
        if (Test-Path $sourcePath) {
          Copy-Item -Path $sourcePath\* -Destination $destinationPath -Recurse -Force
          Write-Host "Files deployed to $destinationPath."
        } else {
          Write-Host "Source directory $sourcePath not found."
        }

    - name: Start Website in IIS
      shell: pwsh
      run: |
        Import-Module WebAdministration
        $appName = '${{ inputs.app-name }}'
        $website = Get-Website | Where-Object {$_.Name -eq $appName}
        if ($website) {
          Start-Website -Name $appName
          Write-Host "Website '$appName' started."
        } else {
          Write-Host "Website '$appName' not found."
        }
