export function Colors()  {
    return  [
        { label: 'Red', value: '#FF0000', icon: 'pi pi-circle' },
        { label: 'Green', value: '#008000', icon: 'pi pi-circle' },
        { label: 'Blue', value: '#0000FF', icon: 'pi pi-circle' },
        { label: 'Yellow', value: '#FFFF00', icon: 'pi pi-circle' },
        { label: 'Orange', value: '#FFA500', icon: 'pi pi-circle' },
        { label: 'Purple', value: '#800080', icon: 'pi pi-circle' },
        { label: 'Cyan', value: '#00FFFF', icon: 'pi pi-circle' },
        { label: 'Magenta', value: '#FF00FF', icon: 'pi pi-circle' },
        { label: 'Lime', value: '#00FF00', icon: 'pi pi-circle' },
        { label: 'Pink', value: '#FFC0CB', icon: 'pi pi-circle' },
        { label: 'Teal', value: '#008080', icon: 'pi pi-circle' },
        { label: 'Lavender', value: '#E6E6FA', icon: 'pi pi-circle' },
        { label: 'Brown', value: '#A52A2A', icon: 'pi pi-circle' },
        { label: 'Beige', value: '#F5F5DC', icon: 'pi pi-circle' },
        { label: 'Maroon', value: '#800000', icon: 'pi pi-circle' },
        { label: 'Mint', value: '#98FF98', icon: 'pi pi-circle' },
        { label: 'Olive', value: '#808000', icon: 'pi pi-circle' },
        { label: 'Coral', value: '#FF7F50', icon: 'pi pi-circle' },
        { label: 'Navy', value: '#000080', icon: 'pi pi-circle' },
        { label: 'Grey', value: '#808080', icon: 'pi pi-circle' },
        { label: 'White', value: '#FFFFFF', icon: 'pi pi-circle' },
        { label: 'Black', value: '#000000', icon: 'pi pi-circle' },
        { label: 'Violet', value: '#EE82EE', icon: 'pi pi-circle' },
        { label: 'Indigo', value: '#4B0082', icon: 'pi pi-circle' },
        { label: 'Gold', value: '#FFD700', icon: 'pi pi-circle' },
        { label: 'Silver', value: '#C0C0C0', icon: 'pi pi-circle' },
        { label: 'Charcoal', value: '#36454F', icon: 'pi pi-circle' },
        { label: 'Peach', value: '#FFE5B4', icon: 'pi pi-circle' },
        { label: 'Salmon', value: '#FA8072', icon: 'pi pi-circle' },
        { label: 'Chocolate', value: '#D2691E', icon: 'pi pi-circle' },
        { label: 'Tomato', value: '#FF6347', icon: 'pi pi-circle' },
        { label: 'Khaki', value: '#F0E68C', icon: 'pi pi-circle' },
        { label: 'Turquoise', value: '#40E0D0', icon: 'pi pi-circle' },
        { label: 'Plum', value: '#DDA0DD', icon: 'pi pi-circle' },
        { label: 'Crimson', value: '#DC143C', icon: 'pi pi-circle' },
        { label: 'Sienna', value: '#A0522D', icon: 'pi pi-circle' },
        { label: 'Orchid', value: '#DA70D6', icon: 'pi pi-circle' },
        { label: 'Azure', value: '#F0FFFF', icon: 'pi pi-circle' },
        { label: 'Ivory', value: '#FFFFF0', icon: 'pi pi-circle' },
        { label: 'Rust', value: '#B7410E', icon: 'pi pi-circle' },
        { label: 'Fuchsia', value: '#FF00FF', icon: 'pi pi-circle' },
        { label: 'Ruby', value: '#E0115F', icon: 'pi pi-circle' },
        { label: 'Amethyst', value: '#9966CC', icon: 'pi pi-circle' },
        { label: 'Pearl', value: '#EAE0C8', icon: 'pi pi-circle' },
        { label: 'Periwinkle', value: '#CCCCFF', icon: 'pi pi-circle' },
        { label: 'Sky Blue', value: '#87CEEB', icon: 'pi pi-circle' },
        { label: 'Mauve', value: '#E0B0FF', icon: 'pi pi-circle' },
        { label: 'Honeydew', value: '#F0FFF0', icon: 'pi pi-circle' },
        { label: 'Azure', value: '#007FFF', icon: 'pi pi-circle' },
      ];
}