name: Deploy apps-accounting app

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: "apps-accounting Deploy"
        required: true
        type: string
        default: 'apps-accounting'
          
      iis-app-name:
        description: "Enter the IIS website name."
        required: true
        type: string
        default: 'apps-accounting'
        
      backup-destination-path:
        description: "Enter the backup destination path."
        required: true
        type: string
        default: 'D:\Backup'

      fe-versions-path:
        description: "Enter The destination path to store FE versions."
        required: true
        type: string
        default: 'D:\FE Versions'

      branch-name:
        required: false
        description: 'Git branch to checkout (default is main)'
        default: 'main'


jobs:
  trigger-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: '${{ inputs.branch-name }}'
          fetch-depth: 0

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Common Build Steps
        uses: ./.github/actions/common-setup/
        with:
          node-version: '18'
          ref: '${{ inputs.branch-name }}'

      - name: Run After Build Action
        uses: ./.github/actions/after-build
        with:
          app-name: ${{ github.event.inputs.app-name }}
          iis-app-name: ${{ github.event.inputs.iis-app-name }}
          backup-destination-path: ${{ github.event.inputs.backup-destination-path }}
          fe-versions-path: ${{ github.event.inputs.fe-versions-path }}
