name: Build and Deploy App

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'The full name of the app to build and deploy (e.g., "apps-accounting")'
        required: true
        default: 'apps-accounting'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: Sprint18
          fetch-depth: 0

      - name: Run Common Setup
        uses: ./.github/actions/common-setup
        with:
          node-version: '18'
          run-as-administrator: true

      - name: Set App Name
        shell: pwsh
        run: |
          $env:APP_NAME = $"{{ github.event.inputs.app-name }}"

      - name: Build App
        shell: pwsh
        run: |
          ng build $env:APP_NAME --configuration production --project=$env:APP_NAME

      - name: Create Destination Directory
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "D:\front\$env:APP_NAME" -Force

      - name: Copy output to D:\front
        shell: pwsh
        run: |
          xcopy /s /y dist\$env:APP_NAME\* D:\front\dist\$env:APP_NAME\
          Write-Host "Apps $env:APP_NAME Deployment successful!"
