name: Build and Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'App name to build (e.g., apps-inventory)'
        required: true

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
        with:
          ref: Sprint18
          fetch-depth: 0
          
      - name: Common Build Steps
        uses: ./.github/actions/common-setup/action.yml
        with:
          node-version: '18'
          ref: Sprint18

      - name: Build App
        run: |
          ng build ${{ github.event.inputs.app-name }}

      - name: Copy output to D:\front
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "D:\front\dist" -Force
          xcopy /s /y dist\* D:\front\dist\
          Write-Host "Deployment successful!"
