name: Build and Deploy Frontend

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'App name to build (e.g., apps-inventory)'
        required: true

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: Sprint18
          fetch-depth: 0

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Common Build Steps
        uses: ./.github/actions/common-setup/
        with:
          node-version: '18'
          ref: Sprint18

      - name: Build App
        run: |
          ng build ${{ github.event.inputs.app-name }}

      - name: Copy output to D:\front
        shell: pwsh
        run: |
          $appName = '${{ github.event.inputs.app-name }}'
          $sourcePath = ".\dist\$appName"
          $destinationPath = "D:\front\dist\$appName"

          if (Test-Path $sourcePath) {
            New-Item -ItemType Directory -Path $destinationPath -Force
            Copy-Item -Path $sourcePath\* -Destination $destinationPath -Recurse -Force
            Write-Host "Deployment successful!"
          } else {
            New-Item -ItemType Directory -Path $destinationPath -Force
            Write-Host "Source directory not found. Creating $appName directory."
            Copy-Item -Path .\dist\* -Destination $destinationPath -Recurse -Force
            Write-Host "Files copied to $appName directory."
          }
