name: Build Finance App

on:
  workflow_dispatch:  

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: Sprint18
          fetch-depth: 0

      
      - name: Run Common Setup
        uses: ./.github/actions/common-setup 
        with:
          node-version: '18'

      - name: Build Finance App
        run: ng build apps-finance --configuration production

      - name: Create Destination Directory
        shell: pwsh
        run: New-Item -ItemType Directory -Path "D:\front\dist\apps-finance" -Force

      - name: Copy output to D:\front
        shell: pwsh
        run: |
          xcopy /s /y dist\apps-finance\* D:\front\dist\apps-finance\
          Write-Host "Apps Finance Deployment successful!"
