name: Build Accounting App

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: Sprint18
          fetch-depth: 0

      # Use the reusable common-setup action
      - name: Run Common Setup
        uses: ./actions.yml # This refers to the action's directory
        with:
          node-version: '18'

      - name: Build Accounting App
        run: ng build apps-accounting --configuration production

      - name: Create Destination Directory
        shell: pwsh
        run: New-Item -ItemType Directory -Path "D:\front\dist\apps-accounting" -Force

      - name: Copy output to D:\front
        shell: pwsh
        run: |
          xcopy /s /y dist\apps-accounting\* D:\front\dist\apps-accounting\
          Write-Host "Apps Accounting Deployment successful!"

      - name: Stop IIS Website
        shell: pwsh
        run: |
          Import-Module WebAdministration
          Stop-WebSite -Name "apps-accounting"
          Write-Host "apps-accounting website stopped"

      - name: Copy files to IIS Directory
        shell: pwsh
        run: |
          xcopy /s /y D:\front\dist\apps-accounting\* C:\inetpub\wwwroot\apps-accounting\
          Write-Host "Files copied to IIS directory"

      - name: Start IIS Website
        shell: pwsh
        run: |
          Import-Module WebAdministration
          Start-WebSite -Name "apps-accounting"
          Write-Host "apps-accounting website started"
