on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Build and Deploy Any Frontend Apps'
        required: true

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: Sprint18
          fetch-depth: 0

      - name: Checkout submodules
        run: git submodule update --init --recursive


      - name: Common Build Steps
        uses: ./.github/actions/common-setup/
        with:
          node-version: '18'
       

      - name: Build App
        run: |
          ng build ${{ github.event.inputs.app-name }}

      - name: After Build Common Steps
        uses: ./.github/actions/after-build/
        with:
          app-name: ${{ github.event.inputs.app-name }}
