name: D-FNx

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Enter an app name or "All" to build and deploy all apps.'
        type: choice
        options:
          - All
          - apps-inventory
          - bussiness-owners
          - adminportal
          - apps-accounting
          - apps-finance
          - apps-hr
          - apps-purchase
          - apps-sales
          - erp-home

      iis-app-name:
          description: 'Enter the IIS website name to stop, backup, deploy, and then start.'
          required: true
      backup-destination-path:
        description: 'Enter the destination path for the website backup.'
        required: true
     
      FE-Versions-path:
        description: 'Enter the FE Versions path .'
        required: true
        

jobs:
  build-and-deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        app-name: ${{ fromJSON(github.event.inputs.app-name == 'All' && '["apps-inventory", "bussiness-owners", "adminportal", "apps-accounting", "apps-finance", "apps-hr", "apps-purchase", "apps-sales", "erp-home"]' || format('["{0}"]', github.event.inputs.app-name)) }}

    steps:
      - name: After Build
        uses: ./.github/actions/after-build/action.yml@Sprint18
