name: Trigger Deploy FR

on:
  workflow_dispatch:
    inputs:
      app-name:
        description: 'Enter an app name or "ALL" to build and deploy all apps.'
        required: true
      iis-app-name:
        description: 'Enter the IIS website name to stop, backup, deploy, and then start.'
        required: true
      backup-destination-path:
        description: 'Enter the destination path for the website backup.'
        required: true

jobs:
  trigger-deploy:
    runs-on: self-hosted
    steps:
      - name: Run after-build custom action
        uses: ./github/actions/after-build
        with:
          app-name: ${{ github.event.inputs.app-name }}
          iis-app-name: ${{ github.event.inputs.iis-app-name }}
          backup-destination-path: ${{ github.event.inputs.backup-destination-path }}
