name: Deploy hr app

on:
  workflow_dispatch:
    inputs:
      branch-name:
        description: "Git branch to checkout (default is main)"
        required: false
        default: "main"

      environment-name:
        description: Environment name (cloud, development, stage, production)
        required: true
        type: choice
        default: development
        options:
          - cloud
          - development
          - stage
          - production

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch-name }}
          fetch-depth: 0

      - name: Reusable Deploy Script
        uses: ./.github/workflows/build-app
        with:
          branch-name: ${{ github.event.inputs.branch-name }}
          environment-name: ${{ github.event.inputs.environment-name }}
          iis-app-name: apps-hr
          iis-app-root-folder: 'C:\inetpub\wwwroot\apps-hr'
